languageCode = "en-us"
baseurl = "terriblecode.com"
title = "TerribleCode by terrible people"
newContentEditor = "vim"
theme = "nofancy"
pygmentsStyle = "native"

[author]
    name = "Eli Uriegas"
    github = "seemethere"
    linkedin = "elias-uriegas"
    twitter = "Eli_ilE"
