baseurl = "http://terriblecode.com/"
theme = "cocoa-eh"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Eli Uriegas"
title = "terriblecode"
disqusshortname = ""
googleAnalytics = "UA-82077088-1"
newContentEditor = "nvim"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Random thoughts about coding and stuff"
copyright = "Copyright © 2017 Eli Uriegas"
logofile = "img/logo.png"
faviconfile = "img/favicon.png"
highlightjs = true
progressively = true
lang = "en"
github = "seemethere"
email = "eliasuriegas@gmail.com"
linkedin = "elias-uriegas"
twitter = "Eli_ilE"
social_banner = "img/logo.png"
latestpostcount = 10
